AllCops:
  Exclude:
    - lib/netsweet/gen/**/*

RaiseArgs:
  Enabled: false

SignalException:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: true
  Max: 20

SpaceAroundEqualsInParameterDefault:
  Enabled: false

NumericLiterals:
  Enabled: false

EmptyLines:
  Enabled: false

Blocks:
  Enabled: false

StringLiterals:
  Enabled: false

ClassLength:
  Enabled: false

# We're not gonna get picky about collect vs. map, inject vs. reduce,
# detect vs. find, or find_all vs. select
CollectionMethods:
  Enabled: false

# Don't force us to write unclear conditionals.
IfUnlessModifier:
  Enabled: false

# Prefer trailing commas in multiline forms to avoid muddied diffs
TrailingComma: # Avoid comma after the last {parameter of a method call, item of a hash}.
  EnforcedStyleForMultiline: comma

# Prefer %r{pathname/} to /pathname\//
RegexpLiteral:
  MaxSlashes: 0
